### ISSUE TITLE
Preview shows "NULL VALUE"

### ISSUE THREAD

**Issue by johntdyer** [smittytone/PreviewYaml#1]
Just installed and I am getting this

<img width="244" alt="image" src="https://user-images.githubusercontent.com/58234/193412779-12e927c0-adf4-468e-972e-c4a6a2f34d0f.png">

I have ensured its checked in settings as instructed during the first run of the application

**Comment by johntdyer** [comment]
restarted finder and it seems happy now... 🤷

**Comment by smittytone** [comment]
Send your sanitised yaml file to support at smittytone.net and I'll see if I can replicate.
