### ISSUE TITLE
Keys not terminated by : in preview

### ISSUE THREAD

**Issue by elektro-wolle** [smittytone/PreviewYaml#2]
The keys were displayed as `NSAttributedString` but without the trailing colon.
It would be nice (for me), if the colon is also displayed.
And, if this is possible: It would be great, if the preview text could be selected (and copied).

**Comment by smittytone** [comment]
I'll look at adding an option to display the colon.

Preview select and copy is controlled by macOS, so that probably won't be added, I'm afraid.

**Comment by elektro-wolle** [comment]
Thanks for the fast reply! Preview-Copy is already enabled (at least on my machine via `defaults write -g QLEnableTextSelection -bool true`) but the textView is not selectable (at least, what I can tell from [PreviewViewController.xib](https://github.com/smittytone/PreviewYaml/blob/main/Yaml%20Previewer/Base.lproj/PreviewViewController.xib#L41))

**Comment by smittytone** [comment]
Update: an option to display the colon is coming in the next release. 

I'm not going to enable copy for the moment because the experience of this with PreviewCode is not ideal (deselecting text is slow), so I'm not rolling the feature out more widely until there's a clear fix for that.
