### ISSUE TITLE
Make text selectable

### ISSUE THREAD

**Issue by o-o-o-o-o** [smittytone/PreviewYaml#4]
Hi There,

Thanks for the app - just purchased it. Is it possible to add making the text selectable in the quicklook window?

**Comment by smittytone** [comment]
It is possible. I'll add it to the to-do list.

**Comment by smittytone** [comment]
This is not going to be done for some time. The experience with PreviewCode is not good (deselecting text is slow) so I won't roll the feature out more widely until there's a clear fix for that.
