### ISSUE TITLE
cool but wtf

### ISSUE THREAD

**Issue by onexbash** [smittytone/PreviewYaml#5]
the preview apps are actually cool but preview yaml uses fcking 14gb RAM on my M1 Mac :D

**Comment by smittytone** [comment]
It shouldn't do -- let me look into that. Is it Yaml Previewer, Yaml Thumbnailer or PreviewYaml that's showing the excessive usage?

**Comment by smittytone** [comment]
Unable to repro. I'd need a copy of the file you're rendering to proceed further.

**Comment by onexbash** [comment]
Sorry, I just went to uninstall and never use it again haha. The preview apps are generally a nice idea, but it would make more sense if you could just brew install preview-code for example and all file types are in it.
I guess the prob was that it was emulated using Rosetta, cause it was not optimized for arm64 macOS but I cant remember.
